id: GitHub Secrets Detection Playbook
version: -1
name: GitHub Secrets Detection Playbook
description: After a secret is found in the GitHub repository, this playbook will require the XSOAR user to see if it is a real secret. Then, an email can be sent out to the commit author to remove the secret and respond.
fromversion: "5.0.0"
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 55400459-0372-4d4b-845d-b6c44e5c9a01
    type: start
    task:
      id: 55400459-0372-4d4b-845d-b6c44e5c9a01
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 96601d8b-06bc-44a6-804b-d5962e04fc09
    type: condition
    task:
      id: 96601d8b-06bc-44a6-804b-d5962e04fc09
      version: -1
      name: Ask user to investigate on the commit
      description: |-
        Please follow the GitHub link to the commit and check whether any potential secrets or secret files are being shared in the source code.

        ${incident.githubcommiturl}

        Are there any secrets leaked? If yes, please also disable this integration instance until the fix.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "No":
      - "2"
      "Yes":
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to: null
      subject: null
      body: {}
      methods: []
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
      replyOptions:
      - "Yes"
      - "No"
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 82a38533-0374-4245-855a-cd2d0c577199
    type: regular
    task:
      id: 82a38533-0374-4245-855a-cd2d0c577199
      version: -1
      name: Close investigation as a false positive
      description: Close the current incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      assetid: {}
      closeNotes:
        simple: No Secret was found
      closeReason:
        simple: False Positive
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingsubtype: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 50b38573-db56-4ecb-8a8c-dab1a52e4dba
    type: condition
    task:
      id: 50b38573-db56-4ecb-8a8c-dab1a52e4dba
      version: -1
      name: Ask the commit author to remove the secrets
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      I have removed the secrets!:
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: ${incident.githubcommitauthoremail}
      subject:
        simple: 'GitHub Secrets detected: ${incident.githubcommiturl}'
      body:
        simple: |-
          Hi ${incident.githubcommitauthorname},

          ${incident.details}

          Please remove the secrets from the commit history, and let us know by clicking the following link.
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
      replyOptions:
      - I have removed the secrets!
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 272906ab-093f-438a-834a-9eb377759dbe
    type: regular
    task:
      id: 272906ab-093f-438a-834a-9eb377759dbe
      version: -1
      name: Confirmation on the secrets removal
      description: |-
        If there are multiple secrets detected in this repository, there will be duplicated incidents created due to the rewritten commit history and a subsequent repository secrets rescan.

        Since this integration instance is disabled, it is advisable to fix all the secrets first and re-enable this integration instance.
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 823d09eb-1677-49a7-8c5f-da609d437ed5
    type: title
    task:
      id: 823d09eb-1677-49a7-8c5f-da609d437ed5
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
